version: "3.7"

services:
  forms_aggregator:
    container_name: "forms-aggregator"
    build: .
    command:
      - pytest
    ports:
      - "4050:4050"
    networks:
      - mongo_form_aggregator

  db_forms_aggregator:
    container_name: "forms-aggregator-db"
    image: mongo:latest
    volumes:
      - ./database/db_forms_aggregator:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - mongo_form_aggregator

  forms_aggregator_mongo_express:
    container_name: "forms_aggregator-mongo-express"
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: "db_forms_aggregator"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - mongo_form_aggregator
    depends_on:
      - db_forms_aggregator

volumes:
  db_forms_aggregator:


networks:
  mongo_form_aggregator:
    driver: bridge
