version: "3.7"

services:
  forms_aggregator_dev:
    container_name: "forms-aggregator-dev"
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "40400:4040"
    networks:
      - mongo

  db_forms_aggregator_dev:
    container_name: "forms-aggregator-dev-db"
    image: mongo
    volumes:
      - ../database/mongo_dev:/data/db
    ports:
      - "5040:27017"
    restart: unless-stopped
    networks:
      - mongo

  forms_aggregator_dev_mongo_express:
    container_name: "forms-aggregator-dev-mongo-express"
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: "db_forms_aggregator"
      ME_CONFIG_BASICAUTH_USERNAME: "root"
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_PORT: "5040"
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - mongo
    depends_on:
      - db_forms_aggregator_dev

volumes:
  db_forms_aggregator_dev:

networks:
  mongo:
    driver: bridge
