version: "3.7"

services:
  forms_aggregator_dev:
    container_name: "forms-aggregator-dev"
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "4040:4040"
    networks:
      - mongo_form_aggregator_dev

  db_forms_aggregator_dev:
    container_name: "forms-aggregator-db-dev"
    image: mongo:latest
    volumes:
      - ./database/db_forms_aggregator_dev:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - mongo_form_aggregator_dev

  forms_aggregator_mongo_express_dev:
    container_name: "forms_aggregator-mongo-express-dev"
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: "db_forms_aggregator_dev"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - mongo_form_aggregator_dev
    depends_on:
      - db_forms_aggregator_dev

volumes:
  db_forms_aggregator_dev:

networks:
  mongo_form_aggregator_dev:
    driver: bridge
